---

- name: Creating Kafka Group | {{ kafkaGroup }}
  group:
    name: "{{ memcached_group }}"
    state: present

- name: Creating Kafka User | {{ kafkaUser }}
  user:
    name: "{{ kafkaUser }}"
    state: present
    group: "{{ kafkaGroup }}"
